config/routes.rb
Rails.application.routes.draw do
  root 'armstrong#index'
  get 'armstrong/index'
  get 'armstrong/input'
  get 'armstrong/result'
  post 'armstrong/result'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/armstrong_controller.rb
class ArmstrongController < ApplicationController
  def index
  end

  def input
  end

  def result
    alert_msg = ''
    notice_msg = ''

    @result = []
    @n = params[:number].to_i

    if @n < 1
      alert_msg = "Number of digits have to be positive value!"
    elsif @n > 39
      notice_msg = "There are no numbers with #{@n} digits"
    elsif @n > 7
      alert_msg = "Very big number of digits. My computer will brake =("
    else
      @result = (10**(@n - 1)).upto(10**@n - 1).select do |num|
        num.digits.reduce(0) {|sum, dig| sum + dig ** @n}.equal? num
      end

      if @result.empty?
        notice_msg = "There are not armstrong numbers with #{@n} digits"
      end
    end

    respond_to do |format|
      format.json do
        render json:
                   {type: @result.class.to_s, value: @result, alert: alert_msg, notice: notice_msg}
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/armstrong_helper.rb
module ArmstrongHelper
end

app/views/armstrong/index.html.erb
<div class="container" align="center">
  <div class="row">
    <div class="col-md-8 offset-md-2 center">
      <h1>Armstrong number</h1>
      <div class="jumbotron">
        In recreational number theory, a narcissistic number (also known as a pluperfect digital invariant (PPDI), an Armstrong number (after Michael F. Armstrong) or a plus perfect number) is a number that is the sum of its own digits each raised to the power of the number of digits. This definition depends on the base b of the number system used, e.g., b = 10 for the decimal system or b = 2 for the binary system.
      </div>
      <%= content_tag 'a', "Let's calculate some of them", role: 'button', class: 'btn btn-primary', href: armstrong_input_path %>
    </div>
  </div>
</div>

app/views/armstrong/input.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2" align="center">
      <h1>Armstrong numbers</h1>

      <div class="form-group">
        <label for="armstrong-input">Number of digits in number</label>
        <input id="armstrong-input" class="form-control" name="number" type="number">
      </div>
      <input type="submit" value="Show numbers" class="btn btn-primary" id="result-btn">

      <div id="result">
        <div id="info"></div>

        <table class="d-none table table-bordered table-hover bg-white" id="armstrong-table">
          <thead class="thead-dark">
            <tr>
              <th>№</th>
              <th >Armstrong number</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/armstrong/result.html.erb
<h1>Armstrong#result</h1>
<p>Find me in app/views/armstrong/result.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <span class="text-muted">Suldin Aleksandr, 2018</span>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <!-- Brand/logo -->
    <%= content_tag :a, 'Armstrong', class: 'navbar-brand', href: root_path %>

    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= content_tag :a, 'Calculate', class: 'nav-link', href: armstrong_input_path %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lr9</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



</head>

<body class="bg-light <%= controller_name %>-<%= action_name %>">
<%= render 'layouts/header' %>
<main class="container" role="main">
  <%= yield %>
</main>
<%= render 'layouts/footer' %>
</body>
</html>